### ISSUE TITLE
error building the master branch

### ISSUE THREAD

**Issue by elikab92** [neo4j/graph-data-science#116]
When I use the `./gradlew packaging:shadowJar` command in the `master` branch I get the following errr:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':neo4j-kernel-adapter:compileJava'.
> Could not resolve all files for configuration ':neo4j-kernel-adapter:compileClasspath'.
   > Could not find org.neo4j:neo4j:.
     Required by:
         project :neo4j-kernel-adapter

```
However, the `1.6` branch compiles.

**Comment by Mats-SX** [comment]
Hello @elikab92 and thanks for reaching out!

Yes, we saw that issue on Tuesday and we believe we fixed it. It should have been pushed over since yesterday. Could you make sure to pull the latest state of the `master` branch and try again? I'm getting a green build from https://github.com/neo4j/graph-data-science/commit/25e9fa3fce99bfb2ceb5496635e83bb618bfe8ac (latest commit at the time of writing).
