### ISSUE TITLE
Documentation modularityOptimization error

### ISSUE THREAD

**Issue by valcarce01** [neo4j/graph-data-science#120]
This algorithm is a beta one so the call for stream should be `gds.beta.modularityOptimization` , as also is when calling from the terminal. However, in the [syntax documentation](https://neo4j.com/docs/graph-data-science/current/algorithms/modularity-optimization/#algorithms-modularity-optimization-syntax), the stream is shown as `gds.modularityOptimization.stream`. All the other examples in the page are well written.
Thank you

**Comment by vnickolov** [comment]
Hello @valcarce01 thank you for pointing this out, we have actually fixed this in our current preview documentation, you can see it [here](https://neo4j.com/docs/graph-data-science/1.7-preview/algorithms/modularity-optimization/#algorithms-modularity-optimization-examples)

We shall cherry-pick the fix for the previous documentation though. 

Thank you once again!
