### ISSUE TITLE
Shortest path relationship id's do not correspond to relathionship id's in the original graph

### ISSUE THREAD

**Issue by KukumavMozolo** [neo4j/graph-data-science#191]
**The Problem**
When computing some shortest Path `relationships(path)` with Yens (or Dijkstra) the algorithm will return similar information about relationships in the path as shown below:

```
[

{
  "identity": -688,
  "start": 3582,
  "end": 3558,
  "type": "PATH_49",
  "properties": {
"cost": 0.5
  }
}

,

{
  "identity": -689,
  "start": 3558,
  "end": 3237,
  "type": "PATH_49",
  "properties": {
"cost": 0.5
  }
}

,

{
  "identity": -690,
  "start": 3237,
  "end": 2858,
  "type": "PATH_49",
  "properties": {
"cost": 0.0
  }
}

,

{
  "identity": -691,
  "start": 2858,
  "end": 2758,
  "type": "PATH_49",
  "properties": {
"cost": 1.0
  }
}

,

{
  "identity": -692,
  "start": 2758,
  "end": 3014,
  "type": "PATH_49",
  "properties": {
"cost": 1.0
  }
}

,

{
  "identity": -693,
  "start": 3014,
  "end": 3369,
  "type": "PATH_49",
  "properties": {
"cost": 0.0
  }
}

,

{
  "identity": -694,
  "start": 3369,
  "end": 3599,
  "type": "PATH_49",
  "properties": {
"cost": 1.0
  }
}

]
```
It looks like the algorithm will introduce new relationships with a new type (PATH_#path number) and a new identity id.
This makes it quite hard to identify the corresponding relationships in the original graph. This is only possible by looking at all relationships between the start and end node and then comparing their costs to the one returned in the path. But this might not lead to a unique solution.
**Describe the solution you would like**
It would be much nicer if the algorithm would return the original relationship id instead of a new one.

**Comment by s1ck** [comment]
Thanks for the request. Unfortunately, we can not provide that information as part of the shortest path result. This is due to the implementation of graph projection. We don't store relationship ids in the in-memory graph, i.e., we can not write back any information to relationships, just to nodes. While this would be possible for native projection, it is not clear how this would work with Cypher projection since relationships could only exist during projection time.

**Comment by KukumavMozolo** [comment]
That's unfortunate. Thanks for your reply though.
