### ISSUE TITLE
Relationship Id mapping from GDS internal to Neo4j

### ISSUE THREAD

**Issue by cuneyttyler** [neo4j/graph-data-science#203]
There is mapping for node Ids in the class IdMap -> toMapOriginalNodeIds. But I couldn't find any similar method for relationships. There are some algorithms where relationships are tracked (such as Dijkstra and Yens). Although this configuration is not used (trackRelationships). I wanted to add relationship ids to the StreamResult but without the mapping it's not possible. Would you be interested in developing this feature?

Thanks.

**Comment by soerenreichardt** [comment]
Hello @cuneyttyler,
You are right, the mapping information for relationships is not stored in GDS. The trackRelationships config option in the shortest path algos invents new relationship ids in order to be able to reconstruct the resulting path with its costs. 
Unfortunately it is currently not planned to add this feature.

**Comment by s1ck** [comment]
I will close the issue since we are not planning to work on this. We put the request in our internal system and might consider it in a future release.
