### ISSUE TITLE
Bug: nodeProjection is misleading when using cypher projection return labels

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#22]
nodeProjection return does not reflect the projected node labels if you use the `labels` with cypher projection.

Create graph:

```
CREATE (:Node)-[:REL]->(:Node),
               (:Label)-[:FOO]->(:Label)
```

Load the graph with cypher projection:

```
CALL gds.graph.create.cypher('cypher',
   'MATCH (n) RETURN id(n) as id, labels(n) as labels',
   'MATCH (a)-[]->(b) RETURN id(a) as source, id(b) as target')
```

The node projection indicates only a single label loaded:

> {
>   "*": {
>     "properties": {
> 
>    },
>    "label": "*"
>   }
> }

But it actually has successfully loaded the labels as we can run the following algorithm:

`CALL gds.pageRank.stream('cypher',{nodeLabels:['Node']})`

And the result includes only two nodes:

nodeId | score
-- | --
1457 | 0.27750000506639483
2411 | 0.15000000000000002

**Comment by Mats-SX** [comment]
@tomasonjo Thanks for reporting this. We think we made a mistake when we made Cypher projections have a generated native projection and return that, as well as list that in `gds.graph.list()`. Our plan to amend this mistake will be to remove the `nodeProjection` and `relationshipProjection` return items from `gds.graph.create.cypher()` and instead have return items `nodeQuery` and `relationshipQuery`. Furthermore, the `nodeProjection` and `relationshipProjection` return items in `gds.graph.list()` will return `null` for Cypher-projected graphs.

The plan is for this to be included in the next release. It will be a breaking change, but we don't think the current behaviour is useful.

In order to describe a Cypher-projected graph in a more useful way than just its formative queries, there is another feature coming, which we are not sure exactly when it will be ready -- but stay tuned.

Does this sound like a good plan to you?

**Comment by tomasonjo** [comment]
I agree that it is better not to show misinformations (`nodeProjection`) and as a step one just show the node and rel queries. 
With the `.mutate` algorithms option it would be nice to look at which properties are available to be written back to the stored graph, so I am looking forward to the new feature!

**Comment by Mats-SX** [comment]
Yes, that feature almost made it into 1.1, but one remaining issue meant we had to postpone it. I'm sorry about the non-inspectability of `.mutate` effects, but hopefully it should not remain an issue for long.

**Comment by Mats-SX** [comment]
@tomasonjo Just FYI the `schema` feature made it into `1.2.0-alpha01`. It is visible via `CALL gds.graph.list() YIELD schema` and also works for Cypher-projected graphs.
