### ISSUE TITLE
[Feature Request] Ignore some labels in native projections

### ISSUE THREAD

**Issue by Cobra5197** [neo4j/graph-data-science#223]
**Is your feature request related to a problem? Please describe.**
Neo4j allows nodes to have multiple labels. My problem is that I wanted to remove nodes from the projection that had a particular label in addition to another label. Example: I have Entity nodes but some are super nodes which I would like to remove from the projection, so I wrote a cypher query to find and set a label to these nodes.

**Describe the solution you would like**
I would like to have for the native projection another configuration parameter which follow the same logic as nodeProjection parameter to ignore nodes that have certain labels.

**Describe alternatives you have considered**
I am using Cypher projection but that is not optimized like native projection:
`MATCH (n:Entity) WHERE NOT n:Super RETURN id(n) AS id, labels(n) AS labels`

**Additional context**
Also, if this feature is developed, in write mode, the ignored nodes property should be set to null. For example, if in write mode I choose the _group as the property name as the result for the algorithm, the ignoreNodes should not have this property because they may have been in the projection before.

Regards,
Cobra

**Comment by vnickolov** [comment]
@Cobra5197 thank you for raising this, we are going to look at it.
In the meantime if this is blocking you, maybe you can invert the labels, what I mean is with the Cypher query that you use to set node label to `Super` you can probably set label `NotSuper` (or something that makes more sense in your domain) and use that label for projection instead.

I hope this helps.

**Comment by Cobra5197** [comment]
Thank you, it's a good idea :)

**Comment by Mats-SX** [comment]
Hello @Cobra5197

We have thought a bit about this feature and we have decided that we will not add it. Behind this decision are a few observations:

- native projections are intentionally limited in their expressivity in order to be simple to understand, use, and optimise
- Cypher projections already offer the increased expressivity (which you also note in your great issue description)
- we are working to improve Cypher projections -- for example, the new Cypher Aggregation alternative that was added in a recent version, but also to make them faster. We prefer to focus our efforts in this direction.
- it is possible to work around the limitation by doing what @vnickolov recommends above
- adding support for this nuanced way of label predicate would satisfy this exact use case, but other predicates such as `X AND Y AND NOT Z` or `X OR Y OR A AND B` (where X, Y, Z, A, B are labels) would not be covered. Cypher projections do cover all such predicates.

I hope this is an acceptable answer.

All the best
Mats
