### ISSUE TITLE
Construction from dataframe, wrong IDs datatype

### ISSUE THREAD

**Issue by Mintactus** [neo4j/graph-data-science#309]
The ID data type or behavior in GDS for dataframe construction with or without arrow is wrong.
Here is why:

Creating IDs from hash values is really useful if not critical sometimes and widely adopted.

The native python hash function is using Int64, and it nativly creates negatives numbers as the Int64 type does.
Polars hash function is using UInt64 and doesn't handle negative integers.
Pandas hash function is using UInt64 and doesn't handle negative integers.

Your implementation of Int64 in GDS cannot handle negatives numbers and it cannot handle huge unsigned positive integers. So we are stuck and this type is useless for most of the ids created by hash functions.

**Comment by knutwalker** [comment]
Hi @Mintactus,

since GDS is implemented in Java and Java does not have unsigned integer types and no primitives to properly emulate an unsigned 64-bit integer, we will not be able to natively support this within GDS.

We recommend to use a hash function that does output either an Int64 or transform the result into an Int64, (e.g. by setting the sign bit to 0 or extending from an UInt32).

**Comment by Mintactus** [comment]
Thanks for the reply, I found a work around, a floor divide by 2 then a
cast. The UInt isn't a bad solution either.
