### ISSUE TITLE
No log with gds.graph.project

### ISSUE THREAD

**Issue by Cobra5197** [neo4j/graph-data-science#328]
Hi, 

I am working on migrating GDS queries from the old way (gds.graph.project.cypher) to the new way (gds.graph.project) and I don't know why, I don't see anymore the progress of the projection in the debug.log file (but I can see the query in the query.log file). The query is working and the graph is well projected. We use Neo4j 4.4.37 and GDS 2.6.8.

GDS version: 4.4.37
Neo4j version: 2.6.8

Best regards,
Cobra

**Comment by soerenreichardt** [comment]
Hello @Cobra5197,
thanks for reporting this. I quickly checked and progress logging is in fact missing in the new `gds.graph.project`. I will create an internal card to add this feature.
However due to the different way of executing the projection, in the new way we currently have no way of knowing how many nodes/relationships will be imported upfront. This means that there will not be any actual progress shown (like 42% etc.), but only that it is running.
Cheers

**Comment by soerenreichardt** [comment]
The code was merged and will appear in the next release of GDS. We managed to find a way so that we will sometimes be able to show actual progress, but in all cases there will be an indication that something is running.
