### ISSUE TITLE
node2vec not replicable despite having a random seed.

### ISSUE THREAD

**Issue by knife982000** [neo4j/graph-data-science#332]
**node2vec not replicable despite having a random seed.**
node2vec is not producing consistent results despite using the same random seed.

**To Reproduce**
All the commands have been executed using Neo4j Web UI.
1. Load the database attached as a [Denmark.txt](https://github.com/user-attachments/files/17130358/Denmark.txt).
2. Map the graph using the following command:
```
MATCH (source)-[r:TRAIN|ROAD]->(target)
WITH source, target, min(r.distance) as d
WITH gds.graph.project(
  'trainOrRoad',
  target,
  source,
  {relationshipProperties: {distance: d }},
  {undirectedRelationshipTypes: ['*']}
) AS g
RETURN g
```
3. Execute multiple times to different results:
```
CALL gds.node2vec.stream('trainOrRoad',
  {
    embeddingDimension: 10,
    randomSeed: 42
  }
)
YIELD nodeId, embedding
RETURN gds.util.asNode(nodeId).name as city, embedding
```

GDS version: 2.9.0
Neo4j version: 5.22.0
Operating system: Linux dockerized version

**Expected behavior**
Multiple execution of the node2vec over the same graph defining a random seed should output the same result.

**Additional context**
n/a
[Denmark.txt](https://github.com/user-attachments/files/17130358/Denmark.txt)

**Comment by IoannisPanagiotas** [comment]
Hi @knife982000,

In general, you should not expect consistency between results when running with concurrency `>1` even when setting a `randomSeed`, because  tasks are being worked on in parallel and this can lead to different results as events can happen in an arbitrary order for each execution.

By default,  when missing, concurreny is set to `4`  as is the case for your example.

Normally  you should be getting consistent  results with `concurrency` set to `1` and fixed`randomSeed`, although it appears  to not be the case for `Node2Vec` .  
With a quick look, I could find some spots where there is arbitrary randomness, though whether or not they are responsible for  the difference in results I cannot say, but I will check a bit more.

Best regards,
Ioannis.

**Comment by knife982000** [comment]
Hi,

you are right. I was checking the test code. Although there is a method checking consistency, it is disabled with the following message: "The order of the randomWalks + its usage in the training is not deterministic yet."

It seems to be a planned feature, but it is not implemented yet. 

Best

**Comment by lassewesth** [comment]
Hey @knife982000 ,

Happened to see you were using Denmark.txt there and wanted to point to this old thing for inspiration: https://lassewesth.blogspot.com/2018/07/the-international-e-road-network-and.html

Good luck!

**Comment by IoannisPanagiotas** [comment]
Hi again @knife982000,

Indeed,   the random walk ordering is one of the reasons why you are getting inconsistent results between runs,  I  am  not sure we could solve this without introducing some slowdowns in performance.

 For the moment, the best we could do was  to make the code return consistent results with random seed, and a concurrency of 1. This will be  in the next version of gds, which should be out  quite soon I believe.

With that, I will close the topic, please let us know if you have any other questions.

Best,
Ioannis.
