### ISSUE TITLE
FeatureRequest: Support for relationship weights in ArticleRank

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#43]
Copied from StackOverflow question: https://stackoverflow.com/questions/61896861/articlerank-appears-to-ignore-relationship-weights. As the title says, the ArticleRank algorithm returns the same results if there are relationships weights provided or not

create sample graph:

```
MERGE (paper0:Paper {name:'Paper 0'})
MERGE (paper1:Paper {name:'Paper 1'})
MERGE (paper2:Paper {name:'Paper 2'})
MERGE (paper3:Paper {name:'Paper 3'})
MERGE (paper4:Paper {name:'Paper 4'})
MERGE (paper5:Paper {name:'Paper 5'})
MERGE (paper6:Paper {name:'Paper 6'})

MERGE (paper1)-[:CITES {weight: 10.0}]->(paper0)

MERGE (paper2)-[:CITES {weight: 1.0}]->(paper0)
MERGE (paper2)-[:CITES {weight: 100.0}]->(paper1)

MERGE (paper3)-[:CITES {weight: 10.0}]->(paper0)
MERGE (paper3)-[:CITES {weight: 1.0}]->(paper1)
MERGE (paper3)-[:CITES {weight: 100.0}]->(paper2)

MERGE (paper4)-[:CITES {weight: 10.0}]->(paper0)
MERGE (paper4)-[:CITES {weight: 1.0}]->(paper1)
MERGE (paper4)-[:CITES {weight: 100.0}]->(paper2)
MERGE (paper4)-[:CITES {weight: 10.0}]->(paper3)

MERGE (paper5)-[:CITES {weight: 100.0}]->(paper1)
MERGE (paper5)-[:CITES {weight: 1.0}]->(paper4)

MERGE (paper6)-[:CITES {weight: 10.0}]->(paper1)
MERGE (paper6)-[:CITES {weight: 100.0}]->(paper4)
```

Run the algorithm with relationships weight:

```
CALL gds.alpha.articleRank.stream({
  nodeProjection: 'Paper',
  relationshipProjection: {
    CITES: {
      properties: 'weight'
    }
  },
  relationshipWeightProperty: 'weight'
})
YIELD nodeId, score
RETURN gds.util.asNode(nodeId).name AS page, score
ORDER BY score DESC
```

or run it without providing the weights:

```
CALL gds.alpha.articleRank.stream({
  nodeProjection: 'Paper',
  relationshipProjection: 'CITES'
})
YIELD nodeId, score
RETURN gds.util.asNode(nodeId).name AS page, score
ORDER BY score DESC
```

The results is in both scenarios the same:

page | score
-- | --
"Paper 0" | 0.3462769146633946
"Paper 1" | 0.31950147982279303
"Paper 4" | 0.21375000253319743
"Paper 2" | 0.21092906260164457
"Paper 3" | 0.18028125041164458
"Paper 5" | 0.15000000000000002
"Paper 6" | 0.15000000000000002

**Comment by jjaderberg** [comment]
copypaste from SO

----

The Article Rank implementation in GDS 1.2 does not support weights.

The documentation is unhelpfully listing a relationshipWeightProperty among the configuration parameters. This is technically correct, because the algorithm configuration does accept this parameter. But the algorithm will ignore it. The reason it looks like this is that a) Article Rank shares API with Page Rank, which does support weights, b) Article Rank is an alpha tier algorithm, so it is not product supported and has not gone through anything like the correctness, performance and usability review of the fully supported algos.

The documentation does go on to say under the heading `Graph type support`, that the algorithm supports:

* directed, unweighted
* undirected, unweighted

**Comment by jjaderberg** [comment]
So I'm noting this as 1) a "docs bug", because the `relationshipWeightProperty` in the config param table is very unhelpful, 2) a feature request for weight support for Article Rank. I think we have a similar situation with "personalized page rank".
I think we can make a docs update reasonably promptly, but I don't know when we would prioritize actually supporting weights in Article Rank.

**Comment by FlorentinD** [comment]
In `1.6` we reworked the implementation of ArticleRank. On of the new features is the support of relationship weights (see https://neo4j.com/docs/graph-data-science/1.6/algorithms/article-rank/#algorithms-article-rank-syntax).
