### ISSUE TITLE
bug: the exported named graph behaves incorrectly

### ISSUE THREAD

**Issue by ThachNgocTran** [neo4j/graph-data-science#50]
There might be an issue with exporting a named graph. I followed this [documentation](https://neo4j.com/docs/graph-data-science/current/management-ops/graph-catalog-ops/#catalog-graph-export), to export a named graph to a Neo4j Database, namely `tempdb`. However, when I made simple queries against `tempdb`, I got strange results: for example, `MATCH (n) RETURN COUNT(n)` returns `0` despite that the named graph has a lot of nodes in there. Same problem with `COUNT(*)`.

<img src="https://user-images.githubusercontent.com/9520123/83730170-fb2b5a80-a648-11ea-9b2e-7ac47b51ccce.png" width="300">

Reproducibility:
+ Neo4j Desktop 4.0.4.
+ The original Neo4j graph (It's from Yelp Dataset):

![expected_schema](https://user-images.githubusercontent.com/9520123/83729957-b273a180-a648-11ea-92e5-a58d1218416f.jpg)

+ The query to generate the named graph:

```
CALL gds.graph.create(
    'my-graph',
    'User',
    {
        FRIEND_OF: {
            type: 'FRIENDS',
            orientation: 'UNDIRECTED'
        }
    }
)
```

+ The stats command (for `tempdb`):

![stat1](https://user-images.githubusercontent.com/9520123/83730301-2ada6280-a649-11ea-8433-ebe4b3211ac7.png)

+ The export command: `CALL gds.beta.graph.export('my-graph', { dbName: 'tempdb' })`

**Comment by knutwalker** [comment]
Hi @ThachNgocTran 

unfortunately, I haven't been able to reproduce the issue.

I ran the following query to create the graph:

```
CALL gds.graph.create('my-graph', 'User', {
    FRIEND_OF: {
        type: 'FRIEND',
        orientation: 'UNDIRECTED'
    }
});
```

which is changed from your query to use `FRIEND` instead of `FRIENDS` as this is the type in the db; it wouldn't allow the loading otherwise.

Then I ran

```
neo4j@yelp> CALL gds.beta.graph.export('my-graph', { dbName: 'tempdb' });
neo4j@yelp> :use system
neo4j@system> CREATE DATABASE tempdb;
neo4j@system> :use tempdb
```

To verify that there are some nodes:

```
neo4j@tempdb> MATCH (n) RETURN n LIMIT 1;
+---------+
| n       |
+---------+
| (:User) |
+---------+
```

And then the count:

```
neo4j@tempdb> MATCH (n) RETURN count(n) LIMIT 1;
+----------+
| count(n) |
+----------+
| 2004214  |
+----------+
```

which matches the expected node count:

```
neo4j@tempdb> :use yelp
neo4j@yelp> MATCH (n:User) RETURN count (n);
+-----------+
| count (n) |
+-----------+
| 2004214   |
+-----------+
```


What version of GDS did you run on? I was using 

```
neo4j@yelp> RETURN gds.version();
+---------------+
| gds.version() |
+---------------+
| "1.2.1"       |
+---------------+
```

and we did some bugfixes around the export procedure. Could you verify that the bug is still present for you on the latest release (which is actually 1.2.2 now) and if so, what queries exactly did you run?

**Comment by ThachNgocTran** [comment]
Hi @knutwalker 

Thank you for the response.

_Following my steps before_, I have just reproduced the issue in my side (Neo4j Desktop v4.0.4, Neo4j engine v4.0.4, APOC v4.0.0.14, Graph Data Science Library v1.2.1, JDK 11.0.7 x64).

However, reading your comment carefully, I found one step of yours, that is different than mine:

+ Yours: `CALL gds.beta.graph.export('my-graph', { dbName: 'tempdb' });` first, then `CREATE DATABASE tempdb;`.
+ Mine: `CREATE DATABASE tempdb;` then `CALL gds.beta.graph.export('my-graph', { dbName: 'tempdb' });`.

**If following your steps, the issue was no longer reproducible**. Everything worked as expected (I could query `MATCH (n) RETURN COUNT(n)`).

**In your steps,** the weird point is that after calling `gds.beta.graph.export()`, I saw a folder named `tempdb` in `c:\Users\[usename]\.Neo4jDesktop\neo4jDatabases\database-f9044750-9863-400a-b173-222f6e4bffb5\installation-4.0.4\data\databases\`. But when `SHOW DATABASES` under `system` user, I didn't see the `tempdb` in the list. I started to see it only after following up with `CREATE DATABASE tempdb`.

In conclusion: when exporting a named graph, the export-to graph, e.g. new_db, must not exist beforehand; and right after exporting, users must `CREATE DATABASE new_db` to officially create the `new_db`.

Rereading the [documentation](https://neo4j.com/docs/graph-data-science/current/management-ops/graph-catalog-ops/#catalog-graph-export), it clearly stated: "**After running the procedure, we can start a new database and query the exported graph**"

```
:use system
CREATE DATABASE mydatabase;
:use mydatabase
MATCH (n) RETURN n;
```

As final words, I think this process seems a bit counter-intuitive and error-prone: export first then create database later! (maybe combining the db creation within the exporting function?) Also, when exporting, if the database already exists, an error should be raised.

**Comment by knutwalker** [comment]
Thanks for the additional check, I can also reproduce it with your steps.

The export procedure will create the new database, but it won't register it with the system database. That's why the manual `CREATE DATABASE` command is needed and that one will register the existing database as useable.
We are adding a note to the documentation to clarify that.
We can't commit to improving that workflow _yet_ since modifying the system db requires different privileges for the procedure.

> Also, when exporting, if the database already exists, an error should be raised.

I agree and it turns out, we had something like that. Unfortunately, the existing check didn't work if the database was empty. We are improving this check to exclude empty databases as well.

You can also fix the exported db by removing the `neostore.counts.db` file from the db directory, but this is a workaround at best, not a solution we would like to propose.
