### ISSUE TITLE
Estimating memory requirements for for write mode of algos requires writeProperty

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#64]
When estimating the memory requirements for a graph algo write mode, the `writeProperty` is mandatory. Maybe we could omit that.

sample graph:

`CREATE (:Node)
`

estimate memory:

```
CALL gds.wcc.write.estimate({nodeProjection:'Node', 
                             relationshipProjection:'*'})
YIELD requiredMemory
```

returns an error:

> Failed to invoke procedure `gds.wcc.write.estimate`: Caused by: java.lang.IllegalArgumentException: No value specified for the mandatory configuration parameter `writeProperty`

**Comment by s1ck** [comment]
We discussed this and decided to not change the signature for estimate mode. The idea is that you use the exact same query you would use for writing / streaming / mutating. It's basically an `EXPLAIN` as in Cypher. Additionally, since we reuse the mode configs for estimate (including validation), the implementation effort would be much higher than the gain.
