### ISSUE TITLE
Enable link prediction on k-hop neighbourhoods

### ISSUE THREAD

**Issue by nabsabraham** [neo4j/graph-data-science#66]
I want to use link prediction algos based on neighbours of neighbours and this is a hyperparameter I'd like to experiment with. Is there a way to do this right now? I understand that the linkpred algos don't use an in memory cypher graph projection so I'm not sure how to do it. (I'm using GDS 1.2)

**Comment by Mats-SX** [comment]
@nabsabraham Hello and thanks for reaching out to us!

I'm not sure exactly what you want to achieve, and I haven't worked extensively with the link prediction algorithms (these are in the alpha tier), but perhaps you can set up your graph so that it fits with the setup you want? I'm thinking a pre-processing query to create direct links between the nodes you identify as "neighbours of neighbours":

```
MATCH (node)-->(neighbour)-->(neighbourOfNeighbour) // some pattern that identifies your interesting link
CREATE (node)-[:POTENTIAL_LINK]->(neighbourOfNeighbour)
```

and then you can call a link prediction such as Adamic Adar such as:

```
MATCH (node1)-[:POTENTIAL_LINK]->(node2)
RETURN gds.alpha.linkprediction.adamicAdar(node1, node2, { relationshipQuery: 'POTENTIAL_LINK' })
```

**Comment by soerenreichardt** [comment]
Closing as this was resolved on another channel.
