### ISSUE TITLE
kNN configuration = {} not working

### ISSUE THREAD

**Issue by waigitdas** [neo4j/graph-data-science#87]
Please see my posting at [Neo4j Community](https://community.neo4j.com/t/graph-data-science-k-nearest-neighbors/27714).

**Comment by Mats-SX** [comment]
Hello @waigitdas and thanks for reaching out to us. I answered in the community forum, but I'll cross-post my reply here also:

----

In order to feed in the properties computed by FastRP you will need to use the mutate mode to add them to the in-memory graph (the one you call 'myGraph'). The write mode will only write them to Neo4j. You can reload them from Neo4j as well, but then you will have to project a new in-memory graph where you also declare the properties, and this is less efficient compared to using mutate.

You can read more about the different execution modes here: https://neo4j.com/docs/graph-data-science/preview/common-usage/running-algos/

----

I've noted that the documentation is wrongfully not covering that `nodeWeightProperty` is a mandatory configuration parameter. We will amend this, thanks for pointing it out!

**Comment by waigitdas** [comment]
Thanks. The in memory graph I created did have the "embedding" property. It was a two step process which was less efficient as you note. But I did have the property in the 2nd iteration of the in memory graph. Yet I still got the error. So I still am puzzled by it not working. Is it a bug or my logic?

**Comment by FlorentinD** [comment]
I will close this issue as it seems to be solved in the community forum.
