### ISSUE TITLE
graphSage returns an array of NaN values as result

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#94]
Seems like this error is completely reproducible, but to load the data I have a Neo4j dump, because there are 50k nodes and 800k rels.

Download and load the Neo4j dump -> https://drive.google.com/file/d/10_YVI5E7xrSZLawnh_oaaTZVZtueud5C/view?usp=sharing 

Load the graph:

```
UNWIND range(0,49) as i
WITH collect('embedding_' + toString(i)) as embeddings
CALL gds.graph.create('train','Train',{INTERACTS:{orientation:'UNDIRECTED'}}, {nodeProperties:embeddings}) YIELD
graphName, nodeCount, relationshipCount
RETURN graphName, nodeCount, relationshipCount
```

train the graphSAGE:

```
UNWIND range(0,49) as i
WITH collect('embedding_' + toString(i)) as embeddings
CALL gds.beta.graphSage.train('train',{
modelName:'proteinModel',
aggregator:'mean',
activationFunction:'relu',
epochs:10,
sampleSizes:[75,25],
featureProperties:embeddings})
YIELD modelInfo
RETURN modelInfo
```

And stream results:

```
CALL gds.beta.graphSage.stream('train', {modelName:'proteinModel'})
YIELD nodeId, embedding
WITH embedding
WHERE any(x in embedding WHERE x <> x)
RETURN * LIMIT 5
```

We get 119 nodes with NaN embeddings:

![embeddin](https://user-images.githubusercontent.com/19948365/101677289-aa177b80-3a5c-11eb-8dfa-9a57335eae09.png)

**Comment by breakanalysis** [comment]
The bug was caused by l2 normalization leading to division by zero.
This can happen if you are embedding a graph that has isolated nodes all of whose properties are `0.0`, and the activation function is relu, since this leads to an all-zero vector for that node.

Fix includes instead returning all-zero vectors in this case, and updating the documentation.
Fix will appear in GDS 1.4.2 and 1.5.0.
